### ISSUE TITLE
Notices to channels aren't filtered

### ISSUE THREAD

**Issue by Mikaela** [jpnurmi/znc-chanfilter#1]
I am on one channel that gets notices often. I am filtering the channel, but I still see the notices in communi-sailfish's server tab. They are statusnotices sent to voiced or higher.

**Comment by jpnurmi** [comment]
https://github.com/jpnurmi/znc-chanfilter/commit/8316463ea1280e0d570534c7d938adc4be8d9c96 should do the trick, but i didn't have time to test yet :)
