### ISSUE TITLE
JOIN 0 actually parts

### ISSUE THREAD

**Issue by farcaller** [jpnurmi/znc-chanfilter#2]
Issuing `JOIN 0` actually **parts** all the channels instead of hiding them.

**Comment by Mikaela** [comment]
This is because `/join 0` is IRCd side command which tells the IRCd to part you from everywhere. I don't think this module or ZNC can do anything to that so this issue is probably invalid.

**Comment by Mikaela** [comment]
I see, so now this module captures that.
